#!/bin/sh
# Add grunt tab-completion if it doesn't exist already

zshrc="$HOME/.zshrc"
bashrc="$HOME/.bashrc"

grunt_tab_check()
{
  gruntcount=`grep -c "grunt --completion=" $1`
  if [ $gruntcount -eq 0 ]
  then
    if [ $1 == $zshrc ]
    then
      echo 'eval "$(grunt --completion=zsh)"' >> $1
    elif [ $1 == $bashrc ]
    then
      echo 'eval "$(grunt --completion=bash)"' >> $1
    fi
    echo 'Grunt tab completion added.'
  fi
}

if [ -e $zshrc ]
then
  grunt_tab_check $zshrc
elif [ -e $bashrc ]
then
  grunt_tab_check $bashrc
else
  echo 'Grunt tab completion was not added to either a .zshrc or .bashrc file.'
fi